name: eosc-454-project
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipywidgets
  - jupyter
  - numpy
  - matplotlib
  - pandas
  - pymatsolver
  - pytest
  - pytorch
  - scikit-learn
  - scipy
  - scooby
  - simpeg
  - sympy

# solver
# uncomment the next line if you are on an intel platform
  # - pydiso # if on intel pc
# uncomment this line if you want to install mumps solvers
  - python-mumps

